### ISSUE TITLE
Adding a sink for Ctrl+Shift+W in addition to Ctrl+W

### ISSUE THREAD

**Issue by trumpetinc** [thalesmello/better-ctrlw#1]
Love that you put this extension together.

One thing that would make it more useful would be to add a second 'Do absolutely nothing' target.

That way we could assign both Ctrl+W and Ctrl+Shift+W.

**Comment by seyeong** [comment]
See https://chrome.google.com/webstore/detail/disable-keyboard-shortcut/aidbmcboeighgdnilpdljbedbbiocphj

**Comment by trumpetinc** [comment]
Thanks, @seyeong - that does exactly what I'm looking for!
