### ISSUE TITLE
Is it possible to config "Site access" in chrome extension setting?

### ISSUE THREAD

**Issue by laseryuan** [thalesmello/better-ctrlw#3]
To disable ctrlw on certain sites only.

**Comment by doggy8088** [comment]
I like this idea. For me, only a few websites are needed to disable ctrl-w hotkey such as GitHub Codespaces or Azure App Editor.

**Comment by thalesmello** [comment]
I don't have much experience with Chrome extensions.
I learned enough just to remap the close tab shortcut.

Closing the issue as this is out of scope of what I want for the project.
