### ISSUE TITLE
is it possible to close tab with shift+click ?

### ISSUE THREAD

**Issue by icyhoty2k** [thalesmello/better-ctrlw#4]
Can shift+click be assigned to close tab , like some ide-s do.
e.x.When you shift click on a tab, active or not it closes.

**Comment by thalesmello** [comment]
Not sure about the feasibility of this

However I just need this extension to remap the close extension shortcut,
so using the mouse is out of scope for this project.

**Comment by icyhoty2k** [comment]
one workaround for people needing thisfunctionality is:
1. downliad autohotkey
2. remap shift +leftclick to middleclick like this:
3. #IfWinActive, ahk_exe chrome.exe 
4. <^LButton::SendInput,  {MButton}
5. #IfWinActive
